# Generated by Django 4.1.3 on 2022-11-04 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uniapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('street', models.CharField(default='name', max_length=200, verbose_name='Street Name')),
                ('city', models.CharField(default='name', max_length=200)),
                ('postal_code', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100, unique=True)),
                ('level', models.CharField(choices=[(1, 'FirstClass'), (2, 'SecondClass'), (3, 'ThirdClass'), (4, 'MasterClass'), (5, 'DoctoralClass')], default=uniapp.models.StudyLevel['FirstClass'], max_length=100)),
                ('speciality', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='name@email.com', max_length=150, null=True, verbose_name='email of group')),
                ('student_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('due', models.DecimalField(decimal_places=2, default=21, max_digits=4)),
                ('model_type', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[(1, 'FirstClass'), (2, 'SecondClass'), (3, 'ThirdClass'), (4, 'MasterClass'), (5, 'DoctoralClass')], default=uniapp.models.StudyLevel['FirstClass'], max_length=100)),
                ('study', models.ManyToManyField(blank=True, to='uniapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='name', max_length=100)),
                ('familyName', models.CharField(default='name', max_length=100)),
                ('password', models.CharField(blank=True, default='name', max_length=100, null=True)),
                ('email', models.EmailField(default='name@email.com', max_length=50, unique=True)),
                ('birthDate', models.DateField(default=datetime.date(2004, 1, 1))),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uniapp.person')),
                ('grade', models.CharField(max_length=200)),
            ],
            bases=('uniapp.person',),
        ),
        migrations.CreateModel(
            name='TeacherModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2022)),
                ('nb_Hours', models.IntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_modules',
            field=models.ManyToManyField(through='uniapp.TeacherModules', to='uniapp.module'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uniapp.person')),
                ('photo', models.ImageField(max_length=200, upload_to='photos/students')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uniapp.address')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uniapp.group')),
            ],
            options={
                'db_table': 'student',
                'ordering': ['name', 'familyName'],
            },
            bases=('uniapp.person',),
        ),
    ]
